### ISSUE TITLE
error TS2343: This syntax requires an imported helper named '__spreadArray' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.

### ISSUE THREAD

**Issue by aladdin-add** [kataw/kataw#17]
```bash
➜  kataw git:(main) ✗ npm run bundle

> kataw@0.0.12 bundle
> cross-env rimraf dist && node scripts/bundle.js

creating normal bundle
writing /home/weiran/repo/kataw/dist/kataw.esm.js
writing /home/weiran/repo/kataw/dist/kataw.umd.js
creating minified bundle
writing /home/weiran/repo/kataw/dist/kataw.esm.min.js
writing /home/weiran/repo/kataw/dist/kataw.umd.min.js
creating normal es5 bundle
/home/weiran/repo/kataw/node_modules/rollup/dist/shared/rollup.js:5279
        base = Object.assign(new Error(base.message), base);
                             ^

Error: src/compiler/utils.ts:37:11 - error TS2343: This syntax requires an imported helper named '__spreadArray' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.

37   return [...array1, ...array2];
             ~~~~~~~~~

    at error (/home/weiran/repo/kataw/node_modules/rollup/dist/shared/rollup.js:5279:30)
    at throwPluginError (/home/weiran/repo/kataw/node_modules/rollup/dist/shared/rollup.js:18240:12)
    at Object.error (/home/weiran/repo/kataw/node_modules/rollup/dist/shared/rollup.js:18847:24)
    at Object.error (/home/weiran/repo/kataw/node_modules/rollup/dist/shared/rollup.js:18409:38)
    at RollupContext.error (/home/weiran/repo/kataw/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17237:30)
    at /home/weiran/repo/kataw/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25030:19
    at arrayEach (/home/weiran/repo/kataw/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:545:11)
    at Function.forEach (/home/weiran/repo/kataw/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9397:14)
    at printDiagnostics (/home/weiran/repo/kataw/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:25006:12)
    at Object.transform (/home/weiran/repo/kataw/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29277:17) {
```

**Comment by KFlash** [comment]
tslib?

**Comment by aladdin-add** [comment]
I guess(not sure) it's because we are using a newer typescript, but rollup-plugin-typescript2 is using a older one.

will try to fix.

**Comment by KFlash** [comment]
or simply stop supporting es5 for now? 

Soon as I get around to fix it, we can run Kataw's source through a ES5 transformer before bundle with Rollup.

**Comment by KFlash** [comment]
Mostly everything depends on the printer as of now. Can't do the transformers before it's done because of some printer logic and unique identifier generation.
